apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: trystan00000/clo835-project-web:latest
          ports:
            - containerPort: 80
