apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: fullstack-app
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
